from mysql.connector import connect, Error
from enum import Enum
import pandas as pd
import os